version: '3'
services:
  web:
    build: .
    ports:
    - "8000:3000"
    command: ['/bin/sh', '-c', 'yarn dev']
  node-server:
    build: .
    ports:
      - "8080:5000"
    command: ['/bin/sh', '-c', 'yarn start']
networks:
  default:
    external:
      name: microservicenetwork